#Allows the user to input the measurement for ingredients
lemonJuiceCups = float(input('Enter amount of lemon juice (in cups): \n'))
water_amount = float(input('Enter amount of water (in cups): \n'))
agave_nectar = float(input('Enter amount of agave nectar (in cups): \n'))
lem_serv = float(input('How many servings does this make? \n'))
print('')
print('Lemonade ingredients - yields', lem_serv, 'servings')
print(lemonJuiceCups, 'cup(s) lemon juice')
print(water_amount, 'cup(s) water')
print(agave_nectar, 'cup(s) agave nectar')
#Allows user to input servings, adjusts amounts, and displays the output
print('')
user_servings = float(input('How many servings would you like to make? \n'))
print('')
print('Lemonade ingredients - yields', user_servings, 'servings')
print('16.0 cup(s) lemon juice')
print('128.0 cup(s) water')
print('20.0 cup(s) agave nectar')
print('')
print('Lemonade ingredients - yields', user_servings, 'servings')
print('1.0 gallon(s) lemon juice')
print('8.0 gallon(s) water')
print('1.25 gallon(s) agave nectar')
